package jitensyaman::Model::hsksyusk;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'jitensyaman::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:database=hsksyusk:host=mysql231.db.sakura.ne.jp',
        user => 'hsksyusk',
        password => 'root16',
    }
);

=head1 NAME

jitensyaman::Model::hsksyusk - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<jitensyaman>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<jitensyaman::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.48

=head1 AUTHOR

User &

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
